### ISSUE TITLE
Replacing libsodium-wrappers

### ISSUE THREAD

**Issue by javisantos** [panva/paseto#11]
Hi @panva! 

only to let you know that i forked this lib to replace libsodium-wrappers for @stablelib modules, the reason is because i didn't want to add more libraries (and weight) to my stack. I know is very subjective, so only if you want i can do a pull request. Just let me know.

Thanks for your amazing work!

**Comment by panva** [comment]
@javisantos it’s important to use a performing, reputable, recognized crypto implementations. 

Ideally, this missing cipher will be added to openssl and therefore also node’s crypto module. Since that’s not the case (yet), libsodium is the second best thing.

**Comment by panva** [comment]
Furthermore, testing the bundle size of your fork it's actually higher and has more module dependencies.

```
❯ du -hs pasetowithstablelib 
1.6M	pasetowithstablelib

~/repo
❯ du -hs paseto 
1.1M	paseto
```

**Comment by javisantos** [comment]
I was just going to verify my expectation, but you did before :) I'll take into consideration, but then i'll have libsodium-wrappers and stablelib if i import paseto to my stack :thinking: . Thanks for the benchmarks
