### ISSUE TITLE
Characters that Paseto uses to create tokens

### ISSUE THREAD

**Issue by pixarfilmz112** [panva/paseto#12]
Hi, so this is what a common paseto token looks like:
` v2.local.rRfHP25HDj5Pda40FwdTsGcsEMoQAKM6ElH6OhCon6YzG1Pzmj1ZPAHORhPaxKQo0XLM5LPYgaevWGrkEy2Os3N68Xee_Me9A0LmbMlV6MNVt-UZMos7ETha`

The characters used are:

- Letters (upper and lower case)
- Numbers
- Special characters (`-`, `_`, `.`)

I was wondering if a token could contain a  slash (`/`, `\`), maybe even other characters?
Thanks

**Comment by panva** [comment]
No. And the why you’ll find in the source specification.
