### ISSUE TITLE
Node 14 bug - TypeError: Cannot read property 'subtle' of undefined (line 10 of crypto_worker.js)

### ISSUE THREAD

**Issue by P-Jay357** [panva/paseto#24]
### What happened?

If the Node version is 14 (have not tested below 14), I get this error when importing V2 Paseto.

If I upgrade to Node 16 then this issue seems fixed, but some of my other packages don't support Node 16 yet, so this isn't ideal.

### Version

v3.0.1

### Node.js Version

v14.17.6

### Code to reproduce

```js
const { V2 } = require('paseto');
```

### 

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/paseto/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
https://github.com/panva/paseto#supported-library-versions

https://github.com/panva/paseto/blob/v3.0.1/package.json#L47-L49
