### ISSUE TITLE
bug: typescript types missing in install

### ISSUE THREAD

**Issue by matthew-nichols-westtel** [panva/paseto#3]
**Describe the bug**
Typescript types aren't included in build on NPM

**To Reproduce**
`npm install paseto` or `yarn add paseto`

**Expected behaviour**
That typescript types be included in `node_modules/paseto/types`

**Environment:**
 - paseto version: [v1.0.2]
 - node version: [v12.10.0]

 - [N/A] the bug is happening on latest paseto version too.
 - [*] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
Thanks, i totally missed that, fixed in v1.0.3
