### ISSUE TITLE
Fails to verify with `complete: true` option if there is no footer.

### ISSUE THREAD

**Issue by ksmithut** [panva/paseto#33]
### What happened?

When trying to extract the footer information from a token that has no footer, the verify call returns a rejected promise.

### Version

3.1.0

### Node.js Version

v18.9.0

### Code to reproduce

```js
import { V4 } from 'paseto'

const key = await V4.generateKey('public', { format: 'paserk' })
const token = await V4.sign({}, key.secretKey)
// This next line fails
const payload = await V4.verify(token, key.publicKey, {
  complete: true
})
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/paseto/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
@ksmithut thank you for this report. v3.1.1 was released with a fix.
