### ISSUE TITLE
Not using ISO8601 Date Format

### ISSUE THREAD

**Issue by frederikbosch** [panva/paseto#42]
### What happened?

`JSON.stringify` does not use a valid ISO8601 date format.

### Version

3.1.2

### Node.js Version

18

### Code to reproduce

```js
const paseto = require('paseto')
const { V3: { sign } } = paseto;

await sign({ 'a' : 'b' }, privateKey, {'expiresIn': '1 year'});
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/paseto/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Please be clearer about the issue and provide clear steps that reproduce and visualize it.

**Comment by frederikbosch** [comment]
Sorry @panva. On a second analysis, the swift-paseto package is not able to read the milliseconds.
