### ISSUE TITLE
Missing type definitions for type imports

### ISSUE THREAD

**Issue by mfbx9da4** [panva/paseto#59]
### What happened?

When attempting to import and use the generateKey function from the paseto package, the function executes correctly at runtime. However, TypeScript raises an error indicating that it cannot find the specified module or its type declarations.

```typescript
import { generateKey } from "paseto/lib/v4/key";
generateKey("public")
```

Typescript error:
```
Cannot find module 'paseto/lib/v4/key' or its corresponding type declarations.ts(2307)
```

I believe there are missing type declarations.

### Version

^3.1.4

### Node.js Version

20

### Code to reproduce

```js
import { generateKey } from "paseto/lib/v4/key";
generateKey("public")
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/paseto/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
That is not how importing this module is intended/documented.

**Comment by mfbx9da4** [comment]
@panva I'd ask you to reconsider as many users will be concerned with bundle size and may not wish to import all of v4 just for verification.
