### ISSUE TITLE
question: Nodejs Crypto vs libsodium

### ISSUE THREAD

**Issue by blelump** [panva/paseto#8]
Hi!

_Problem_: lack of compatibility(?) between generated private keys via Nodejs Crypto module and various libsodium implementations.

It seems that Nodejs Crypto expects 48 bytes length keys whereas libsodium implementations provide 64 bytes length private keys. Of course due to that fact `const token = await sign({ sub: 'johndoe' }, privateKey)` fails.

Already stated a question on Nodejs https://github.com/nodejs/help/issues/2543 help repo, but perhaps you could put more light on this problem, maybe I'm just missing something?

A low level example of the problem:
```
'use strict';

var sodium = require('sodium-native')
const paseto = require('paseto');
const { V2 } = paseto
const { V2: { sign } } = paseto
const crypto = require('crypto')
const { promisify } = require('util')
const generateKeyPair = promisify(crypto.generateKeyPair)
const {
  createPrivateKey,
  KeyObject
} = require('crypto');


let pk = Buffer.alloc(32);
let sk = Buffer.alloc(64);

// Create key pair with libsodium impl:
sodium.crypto_sign_keypair(pk, sk);

console.log(sk.length);

(async () => {
  const { privateKey } = await generateKeyPair('ed25519')
  const exp = privateKey.export({ type: 'pkcs8', format: 'der' });
  console.log(exp.length)

  // Try to instantiate Crypto private key from the one generated via libsodium:
  // Here it will fail with Error: error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long
  createPrivateKey({ key: sk, format: 'der', type: 'pkcs8' }); 


})();
```

**Comment by panva** [comment]
I think you’re missing the fact that node does not work with arbitrary raw keys but DER/PEM encoded ones.

**Comment by blelump** [comment]
@panva do you have any suggestion to overcome this?

**Comment by panva** [comment]
1) get the 32 byte private key raw value from sodium
2) encode it as per pkcs8 (see the link for parsed DER structure above)

**Comment by blelump** [comment]
@panva , thanks for help!

This one "passes":
```
'use strict';

var sodium = require('sodium-native')
const crypto = require('crypto')
const { promisify } = require('util')
const generateKeyPair = promisify(crypto.generateKeyPair)
const {
  createPrivateKey,
  KeyObject
} = require('crypto');
const asn1 = require('./node_modules/jose/lib/help/asn1')
const OneAsymmetricKey = asn1.get('OneAsymmetricKey')

let pk = Buffer.alloc(32);
let sk = Buffer.alloc(64);

sodium.crypto_sign_keypair(pk, sk);

let sk_cp = sk.slice(0, 32);

const b64 = OneAsymmetricKey.encode({
  version: 0,
  privateKey: { privateKey: sk_cp },
  algorithm: { algorithm: '1.3.101.112'.split('.') }
}, 'der');
b64.write('04', 12, 1, 'hex');

const priv = createPrivateKey({ key: b64, format: 'der', type: 'pkcs8' });
console.log(priv)
```

but the way it is currently done bothers me a lot as it is an extraction of the library internals. Anything in your mind that could improve this conversion to DER? Meanwhile I'm looking for some out of the box solution, but kinda green field for me.

**Comment by panva** [comment]
That's why i said walk back the code, to reimplement it using e.g. `asn1.js` yourself, your own code. What you're requiring are internals and I do not recommend anyone doing so.

**Comment by blelump** [comment]
Thanks @panva ! Wouldn't solve this without your help, appreciate that!

First tried to find something out of the box and got into https://github.com/digitalbazaar/forge with asn1 encode/decode, but then following your comment from the above link https://github.com/panva/jose/blob/v1.25.0/lib/help/key_utils.js#L287  ended up with updated example above only with dependency to `asn1.js`.

**Comment by somdoron** [comment]
I sign the token with another library (libsodium) in another language (scala) and verify using this library. I have spent the entire day trying to convert libsodium ed25519 public key to something nodejs crypto module can understand, eventually, I end up with the following:

```
const {createPublicKey} = require("crypto");

const der = Buffer.concat([Buffer.from("302a300506032b6570032100", "hex"), libsodiumPublicKey]);
const publicKey = createPublicKey({
    key: der,
    format: "der",
    type: "spki"
});
```

I thought it might help someone else in the future.

**Comment by panva** [comment]
If libsodium supported actual [ASN.1 encoded keys](https://lapo.it/asn1js/#MCowBQYDK2VwAyEA_-nF2BNwDIz2sj_gulyjyfFmUXv3a1KZ2Go9TT-y6l8) rather than arbitrary binary data as keys you'd be set. Anyway libsodium <> openssl (ASN.1) conversion is not of concern to this lib, ASN.1 is a used standard for a good reason. The code @somdoron works for ed25519 public keys tho. It won't work for private ones.

**Comment by somdoron** [comment]
I agree, libsodium supporting ASN.1 would be nice and would save me a day. Yes, I know it only works for public keys (I'm currently not concerned with private keys at the moment).
