### ISSUE TITLE
stuck on key length error

### ISSUE THREAD

**Issue by hawk-ee** [panva/paseto#9]
```javascript
const keyword = "..."

const key = crypto.createSecretKey(Buffer.from(keyword, "base64"));

key.byteLength // >= 32

V2.encrypt(payload, key);
// V2.local secret key must be 32 bytes long symmetric key
```
Always get this error even when the secret is long enough.

**Comment by hawk-ee** [comment]
`symmetricKeySize` and `asymmetricKeySize` props of the KeyObject generated are both undefined.
Running node 12.16.1

**Comment by panva** [comment]
https://nodejs.org/docs/latest-v12.x/api/crypto.html#crypto_keyobject_symmetrickeysize

KeyObjects do not have ‘byteLength’ as your code suggests.

I can’t reproduce this report.

**Comment by hawk-ee** [comment]
```javascript
require("crypto")
  .createSecretKey( Buffer.from("...", "base64") )
  .symmetricKeySize // undefined
```
Wrong code srry. The `symmetricKeySize` property is undefined. Running the same code on console  returns its size. Any idea?

**Comment by panva** [comment]
The code without the property is not using node 12

**Comment by hawk-ee** [comment]
Node 12.16.1. Anyway it's something related to node.

**Comment by panva** [comment]
You asked if I had an idea. Your console is node 12, whatever else you run the code in where it doesn’t work is a different version. 

Put a console.log(process.versions) in the code and see the difference.

**Comment by hawk-ee** [comment]
@panva  just to check... The func `checkKey` receives two args (header, key), but key is passed as the first argument here:

/lib/V2/encrypt.js
```js
  payload = checkPayload(payload)
  key = checkKey(key) // <<
```
/lib/V2/help/symmetric_key_check.js
```js
function checkKey (header, key) {
  if (!(key instanceof KeyObject)) {
    key = createSecretKey(key)
  }

  if (key.type !== 'secret' || key.symmetricKeySize !== 32) {
    throw new TypeError(`${header} secret key must be 32 bytes long symmetric key`)
  }
```

Is this correct?
I think this combined to the [wrong type of symmetricKeySize](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/0d1f0239acbbd6356a79f1c0f1e33cec1f283745) popping on vscode confused me :laughing: .

**Comment by panva** [comment]
[Yes it is used correctly](https://github.com/panva/paseto/blob/master/lib/v2/encrypt.js#L3)

**Comment by hawk-ee** [comment]
Only one node version, latest lts. Idk which lib included node typing. Now it works, just tired I guess. thanks for you help

**Comment by panva** [comment]
I don't see what typings have to do with runtime results but okay.
